---
# This playbook deploys the whole application stack in this site.

- name: apply to RPi
  hosts: rpi
  remote_user: pi
  become: True

  roles:
    - common
    - infrared
    - webremocon
    - mailcron
    - envsensor
