---
- name: apt-get update
  apt: update_cache=yes

- name: Install common utilities
  apt: name={{ itme }} state=present
  with_items:
   - vim
   - git

- name: apt-get upgrade
  apt: upgrade=yes

- name: fix /etc/localtime
  copy:
    src: /usr/share/zoneinfo/{{ item.area }}
    dest: /etc/localtime
  with_items: rpi_config_options

- name: fix /etc/timezone
  linefile:
    dest: /etc/timezone
    regexp: "*"
    line: "{{ item.area }}"
  with_items: rpi_config_options


# - name: wifi network config
  # when: use_wifi == "yes"
