---
- name: apt-get update
  apt: update_cache=yes

- name: Install common utilities
  apt: name={{ item }} state=present
  with_items:
   - vim
   - git

- name: apt-get upgrade
  apt: upgrade=yes

- name: fix /etc/localtime
  copy:
    src: /usr/share/zoneinfo/{{ area }}
    dest: /etc/localtime

- name: template /etc/timezone
  template:
    src: timezone.j2
    dest: /etc/timezone


# - name: wifi network config
  # when: use_wifi == "yes"
